### ISSUE TITLE
netherex nether wart config 

### ISSUE THREAD

**Issue by chunkedelement** [chunkedelement/Compendium-VTF#10]
https://github.com/LogicTechCorp/NetherEx/issues/127
will check as the default has a visual planting issue where u can plant but the nether wart item vanishes?

**Comment by Thunder-Nova** [comment]
It's the illusion that the n.warts vanishes. It's still in the inventory as if never placed.

To plant nether warts is to tilt soul sand and plant the warts. And if I recall. The farm requires lava near it.

**Comment by LogicTechCorp** [comment]
Nether Wart growth will be changed back to the Vanilla system in NetherEx's upcoming release.

**Comment by chunkedelement** [comment]
Addressed by Dev, version 1.2.0b
