### ISSUE TITLE
Padding Sound Bug - Dark Helm and Ender Helm

### ISSUE THREAD

**Issue by Thunder-Nova** [chunkedelement/Compendium-VTF#12]
Do not use Padding addon onto your Dark Helm/Ender Helm. It bypasses the muffler, can still hear sound, and some sounds won't go until in-game volume goes 0 and back (which removes the repeating sound).

https://github.com/SleepyTrousers/EnderIO/issues/5088

**Comment by chunkedelement** [comment]
overrides/config/enderio/EnderIO.cfg

**Comment by chunkedelement** [comment]
https://github.com/chunkedelement/Compendium-VTF/commit/9a5b9497afcec3923ca3291708441a286fa4f109

**Comment by chunkedelement** [comment]
It looks like this was fixed in version 5.0.44 of Ender IO.
The changelog says “Fixed step assist logic.”

**Comment by chunkedelement** [comment]
https://github.com/SleepyTrousers/EnderIO/commit/07d510b3dc677d7ef09b65b01dfc255816e1b934

**Comment by chunkedelement** [comment]
This still is not working properly as no way to disable padding upgrade(s) completely in enderio config.

**Comment by chunkedelement** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/5318

**Comment by chunkedelement** [comment]
It looks like this was fixed in version 5.0.44 of Ender IO.
The changelog says “Fixed step assist logic.”
