### ISSUE TITLE
Cannot convert some blocks back to ingots

### ISSUE THREAD

**Issue by jonochar** [chunkedelement/Compendium-VTF#8]
Cannot convert some blocks back to their ingot form I've only come across these two so far: Block of Copper and Block of Tin. This did not work with the player inventory or the crafting table.

**Comment by chunkedelement** [comment]
ok will check, thanks for posting, you can temp grind up the cubes in the sag mill to convert or smash the cubes with the crackhammer, or use the TE factorizor (prob best option), but its prob a recipe conflict trying to locate, the next update should address this.

**Comment by chunkedelement** [comment]
i think this may be related to the copper/silver conversations with basemetals/TE/mekanism/embers/ project red: https://github.com/WanionCane/UniDict/issues/133

**Comment by chunkedelement** [comment]
https://github.com/chunkedelement/Compendium-VTF/pull/9/commits/1ae12eac603e339b46b4f3d69ab64ba6eed6d2a4

**Comment by chunkedelement** [comment]
c4cc6b3a8b83cb184e504e613c98060960541f78

**Comment by chunkedelement** [comment]
https://github.com/chunkedelement/Compendium-VTF/commit/9d6a04a627fe3d75aa549139fa1ac3f04b4dbffb

**Comment by chunkedelement** [comment]
v1.0.9 ore recipes updated, should be addressed.

**Comment by chunkedelement** [comment]
should be addressed in latest 1.1.0 update, closing for now thanks.
